apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi-karpenter-{{ ts_nodash }}
  namespace: spark-operator
  labels:
    app: "pyspark-pi"
    applicationId: "pyspark-pi-karpenter"
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "public.ecr.aws/data-on-eks/spark:3.5.3-scala2.12-java17-python3-ubuntu"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.3"
  arguments:
    - "100"
  sparkConf:
    "spark.driver.extraJavaOptions": "-Dlog4j.rootCategory=WARN,console"
    "spark.executor.extraJavaOptions": "-Dlog4j.rootCategory=WARN,console"
    "spark.ui.prometheus.enabled": "true"
    "spark.executor.processTreeMetrics.enabled": "true"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.driver.sink.prometheusServlet.path": "/metrics/driver/prometheus/"
    "spark.metrics.conf.executor.sink.prometheusServlet.path": "/metrics/executors/prometheus/"
    "spark.kubernetes.scheduler.name": "yunikorn"
    "spark.kubernetes.driver.label.queue": "root.default"
    "spark.kubernetes.executor.label.queue": "root.default"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20

  driver:
    cores: 1
    coreRequest: "500m"
    coreLimit: "1000m"
    memory: "1g"
    memoryOverhead: "512m"
    labels:
      version: 3.5.3
    serviceAccount: spark-sa
    nodeSelector:
      "karpenter.sh/capacity-type": "on-demand"
      "workload-type": "spark"
    tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "spark"
        effect: "NoSchedule"

  executor:
    cores: 1
    coreRequest: "800m"
    coreLimit: "1000m"
    memory: "3g"
    memoryOverhead: "512m"
    serviceAccount: spark-sa
    labels:
      version: 3.5.3
    nodeSelector:
      "workload-type": "spark"
    tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "spark"
        effect: "NoSchedule"

  dynamicAllocation:
    enabled: true
    initialExecutors: 2
    maxExecutors: 4
    minExecutors: 2
