apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi-karpenter
  namespace: spark-team-a
  labels:
    app: "pyspark-pi"
    applicationId: "pyspark-pi-karpenter"
    # Assign the job to a Yunikorn Queue via label.
    queue: root.test
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "public.ecr.aws/data-on-eks/spark:3.5.3-scala2.12-java17-python3-ubuntu"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.3"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.3
    serviceAccount: spark-sa
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand"
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    serviceAccount: spark-sa
    labels:
      version: 3.5.3
