apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi-karpenter
  namespace: spark-operator
  labels:
    app: "pyspark-pi"
    applicationId: "pyspark-pi-karpenter"
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "public.ecr.aws/data-on-eks/spark:3.5.3-scala2.12-java17-python3-ubuntu"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.3"
  arguments:
  - "1000"
  sparkConf:
    "spark.driver.extraJavaOptions": "-Dlog4j.rootCategory=WARN,console"
    "spark.executor.extraJavaOptions": "-Dlog4j.rootCategory=WARN,console"
    # Expose Spark metrics for Prometheus
    "spark.ui.prometheus.enabled": "true"
    "spark.executor.processTreeMetrics.enabled": "true"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.driver.sink.prometheusServlet.path": "/metrics/driver/prometheus/"
    "spark.metrics.conf.executor.sink.prometheusServlet.path": "/metrics/executors/prometheus/"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  batchScheduler: yunikorn
  batchSchedulerOptions:
    queue: root.default
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.3
    serviceAccount: spark-sa
    # the c5d instances that Karpenter will launch will have the NVMe storage preformatted and available to the pod
    # we do not need to leverage a hostPath mount or volume to leverage that storage.
    # ephemeral-storage requests and limits can be used to manage the storage utilization
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand"
      provisioner-name: "spark-compute"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    serviceAccount: spark-sa
    labels:
      version: 3.5.3
    nodeSelector:
      karpenter.sh/capacity-type: "spot"
      provisioner-name: "spark-compute"
  dynamicAllocation:
    enabled: true
    initialExecutors: 3
    maxExecutors: 10
    minExecutors: 1
